name: CI/CD - PHP App (Simple)

on:
  push:
    branches:
      - main
      - dev

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ github.ref == 'refs/heads/dev' && 'ghcr.io/anantakumarshrestha/php-app:dev' || 'ghcr.io/anantakumarshrestha/php-app:prod' }},
                ${{ github.ref == 'refs/heads/dev' && 'ghcr.io/anantakumarshrestha/php-app:latest-dev' || 'ghcr.io/anantakumarshrestha/php-app:latest-prod' }}

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Dev
        if: github.ref == 'refs/heads/dev'
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ghcr.io/anantakumarshrestha/php-app:dev
            docker stop php-app || true
            docker rm php-app || true
            docker run -d --name php-app -p 8080:80 ghcr.io/anantakumarshrestha/php-app:dev

      - name: Deploy Prod
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ghcr.io/anantakumarshrestha/php-app:prod
            docker stop php-app || true
            docker rm php-app || true
            docker run -d --name php-app -p 8081:80 ghcr.io/anantakumarshrestha/php-app:prod
